### ISSUE TITLE
Failed to compile shaders

### ISSUE THREAD

**Issue by CarstenOst** [jossomjod/jossomjod.github.io#1]
Uncaught TypeError: Failed to execute 'attachShader' on 'WebGLRenderingContext': parameter 2 is not of type 'WebGLShader'.
    at initShaderProgram (functions.js:43:5)
    at main.js:20:2

https://github.com/jossomjod/jossomjod.github.io/blob/4f032130f46e015fd0a2608027c03805e257fdd8/scripts/functions.js#L43

**Comment by jossomjod** [comment]
Hmm... April 1st. Nice try, bro.
Also, if you're trying to run this on mobile, just give up.

**Comment by jossomjod** [comment]
nvm, it's a real error. Seems like Chrome is having trouble with the fragment shader.
Workaround: Use Firefox.

**Comment by jossomjod** [comment]
Fixed.
And it somehow works on mobile now wtf
